{{- if and .Values.podDisruptionBudget.backend.enabled (gt (int .Values.backend.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openvpn-control.fullname" . }}-backend
  labels:
    {{- include "openvpn-control.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  selector:
    matchLabels:
      {{- include "openvpn-control.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}

