{{- if and .Values.podDisruptionBudget.frontend.enabled (gt (int .Values.frontend.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openvpn-control.fullname" . }}-frontend
  labels:
    {{- include "openvpn-control.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  selector:
    matchLabels:
      {{- include "openvpn-control.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}

