apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn-control.fullname" . }}-postgres
  labels:
    {{- include "openvpn-control.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "openvpn-control.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
