apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-control.fullname" . }}-secrets
  labels:
    {{- include "openvpn-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ required "values.postgres.password is required" .Values.postgres.password | quote }}
  jwt-secret: {{ required "values.backend.jwtSecret is required" .Values.backend.jwtSecret | quote }}
  init-admin-password: {{ required "values.backend.initAdminPassword is required" .Values.backend.initAdminPassword | quote }}
