package openvpn

// InitialServerSettings is the seed when the agent is unreachable.
func InitialServerSettings() map[string]any {
	return map[string]any{
		"port":                   1194,
		"proto":                  "udp",
		"dev":                    "tun0",
		"remote":                 "{{host}} {{port}}",
		"resolv-retry":           "infinite",
		"nobind":                 true,
		"key-direction":          "{{key_direction}}",
		"topology":               "subnet",
		"local":                  "",
		"daemon":                 false,
		"mode":                   "server",
		"server":                 "10.8.0.0 255.255.255.0",
		"server-bridge":          "",
		"max-clients":            100,
		"keepalive":              "10 120",
		"ca":                     "",
		"cert":                   "",
		"key":                    "",
		"dh":                     "",
		"ecdh-curve":             "",
		"tls-auth":               "",
		"tls-crypt":              "",
		"tls-crypt-v2":           "",
		"crl-verify":             "",
		"remote-cert-tls":        "",
		"verify-x509-name":       "",
		"management":             "",
		"status":                 "",
		"log":                    "",
		"log-append":             "",
		"plugin":                 []any{},
		"up":                     "",
		"down":                   "",
		"persist-key":            true,
		"persist-tun":            true,
		"duplicate-cn":           false,
		"client-to-client":       false,
		"float":                  false,
		"data-ciphers":           "AES-256-GCM:AES-128-GCM",
		"tls-ciphersuites":       "",
		"cipher":                 "",
		"auth":                   "SHA256",
		"tls-version-min":        "1.2",
		"verb":                   3,
		"client-verb":            3,
		"mute":                   20,
		"mute-replay-warnings":   false,
		"script-security":        2,
		"reneg-sec":              0,
		"hand-window":            60,
		"tun-mtu":                1500,
		"mssfix":                 1450,
		"fragment":               0,
		"user":                   "nobody",
		"group":                  "nogroup",
		"ifconfig-pool-persist":  "",
		"comp-lzo":               "",
		"allow-compression":      "",
		"panelRootCaId":          "",
		"panelServerCertId":      "",
		"panelDhMaterialId":      "",
		"panelTlsAuthMaterialId": "",
		"push":                   []any{},
		"route":                  []any{},
	}
}
