ALTER TABLE "AgentNode"
ADD COLUMN "diskReadBps" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "diskWriteBps" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "AgentMetricSnapshot"
ADD COLUMN "diskReadBps" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "diskWriteBps" DOUBLE PRECISION NOT NULL DEFAULT 0;
