map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _ localhost;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    include /etc/nginx/conf.d/snippets/proxy.inc;
}