server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _ localhost;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}