import type { SettingsFieldMeta } from "./types/settingsMeta";

/**
 * Метаданные полей server.conf, синхронизированные с агентом (managed directives).
 * key — имя директивы OpenVPN (в нижнем регистре).
 */
export const OPENVPN_SERVER_SETTINGS_FIELDS: SettingsFieldMeta[] = [
  {
    key: "port",
    label: "Порт",
    description: "Порт, на котором OpenVPN слушает клиентов (UDP или TCP).",
    type: "number",
    placeholder: "1194",
  },
  {
    key: "proto",
    label: "Протокол",
    description: "Транспорт: udp, tcp, udp6, tcp6.",
    type: "select",
    options: [
      { value: "udp", label: "UDP" },
      { value: "tcp", label: "TCP" },
      { value: "udp6", label: "UDP6" },
      { value: "tcp6", label: "TCP6" },
    ],
  },
  {
    key: "dev",
    label: "Тип / имя TUN/TAP",
    description: "Например tun0, tap0 или tun — имя виртуального интерфейса.",
    type: "text",
    placeholder: "tun0",
  },
  {
    key: "remote",
    label: "Remote (клиентский профиль)",
    description: "Адрес и порт сервера для генерации клиентского .ovpn, например vpn.example.com 1194.",
    type: "text",
    placeholder: "{{host}} {{port}}",
  },
  {
    key: "resolv-retry",
    label: "Resolv-retry (клиентский профиль)",
    description: "Повтор DNS-резолва в клиентском профиле (например infinite).",
    type: "text",
    placeholder: "infinite",
  },
  {
    key: "nobind",
    label: "Nobind (клиентский профиль)",
    description: "Не привязывать фиксированный локальный порт в клиентском профиле.",
    type: "checkbox",
  },
  {
    key: "key-direction",
    label: "Key-direction (клиентский профиль)",
    description: "Направление для tls-auth в клиентском .ovpn (0|1).",
    type: "text",
    placeholder: "{{key_direction}}",
  },
  {
    key: "topology",
    label: "Топология",
    description: "Режим адресации VPN-подсети: subnet (рекомендуется), net30, p2p.",
    type: "select",
    options: [
      { value: "subnet", label: "subnet" },
      { value: "net30", label: "net30" },
      { value: "p2p", label: "p2p" },
    ],
  },
  {
    key: "local",
    label: "Local",
    description: "Локальный адрес привязки (директива local), например 10.0.2.3.",
    type: "text",
    placeholder: "10.0.2.3",
  },
  {
    key: "daemon",
    label: "Daemon",
    description: "Запуск в фоне (директива daemon без аргументов).",
    type: "checkbox",
  },
  {
    key: "mode",
    label: "Mode",
    description: "Режим процесса OpenVPN, для сервера обычно server.",
    type: "select",
    options: [
      { value: "", label: "— не задано" },
      { value: "server", label: "server" },
      { value: "p2p", label: "p2p" },
    ],
  },
  {
    key: "server",
    label: "Сервер (сеть VPN)",
    description: "Две части: адрес сети и маска, например 10.8.0.0 255.255.255.0",
    type: "text",
    placeholder: "10.8.0.0 255.255.255.0",
  },
  {
    key: "server-bridge",
    label: "Server-bridge",
    description: "Для режима моста (Ethernet): параметры bridge, если используется tap+bridge.",
    type: "text",
    placeholder: "",
  },
  {
    key: "max-clients",
    label: "Макс. клиентов",
    description: "Ограничение одновременных подключений.",
    type: "number",
    placeholder: "100",
  },
  {
    key: "keepalive",
    label: "Keepalive",
    description: "Два числа через пробел: ping и ping-restart (сек), например 10 120.",
    type: "text",
    placeholder: "10 120",
  },
  {
    key: "ca",
    label: "ca (корневой сертификат)",
    description: "Путь к файлу корневого сертификата (директива OpenVPN ca), например /etc/openvpn/ca.crt.",
    type: "text",
    placeholder: "/etc/openvpn/ca.crt",
  },
  {
    key: "cert",
    label: "Cert",
    description: "Путь к сертификату сервера.",
    type: "text",
    placeholder: "/etc/openvpn/server.crt",
  },
  {
    key: "key",
    label: "Key",
    description: "Путь к закрытому ключу сервера.",
    type: "text",
    placeholder: "/etc/openvpn/server.key",
  },
  {
    key: "dh",
    label: "DH",
    description: "Путь к файлу Диффи-Хеллмана (если не используется только ecdh-curve).",
    type: "text",
    placeholder: "/etc/openvpn/dh.pem",
  },
  {
    key: "ecdh-curve",
    label: "ECDH-curve",
    description: "Кривая для ECDH (альтернатива/дополнение к dh в зависимости от версии и конфигурации).",
    type: "text",
    placeholder: "secp384r1",
  },
  {
    key: "tls-auth",
    label: "TLS-auth",
    description: "Файл статического ключа и при необходимости направление (0|1), например /etc/openvpn/ta.key 0.",
    type: "text",
    placeholder: "/etc/openvpn/ta.key 0",
  },
  {
    key: "tls-crypt",
    label: "TLS-crypt",
    description: "Путь к файлу tls-crypt (если используется вместо tls-auth).",
    type: "text",
    placeholder: "",
  },
  {
    key: "tls-crypt-v2",
    label: "TLS-crypt-v2",
    description: "Путь к ключу tls-crypt-v2.",
    type: "text",
    placeholder: "",
  },
  {
    key: "crl-verify",
    label: "CRL-verify",
    description: "Путь к отозванным сертификатам (CRL).",
    type: "text",
    placeholder: "/etc/openvpn/crl.pem",
  },
  {
    key: "remote-cert-tls",
    label: "Remote-cert-tls",
    description: "Ожидаемый тип удалённого сертификата у клиента (обычно client для сервера).",
    type: "select",
    options: [
      { value: "", label: "— не задано" },
      { value: "client", label: "client" },
      { value: "server", label: "server" },
    ],
  },
  {
    key: "verify-x509-name",
    label: "Verify-x509-name",
    description: "Проверка имени в сертификате клиента, например CN или формат из man openvpn.",
    type: "text",
    placeholder: "",
  },
  {
    key: "management",
    label: "Management",
    description: "Интерфейс management: IP порт [pw-file], например 127.0.0.1 7505.",
    type: "text",
    placeholder: "127.0.0.1 7505",
  },
  {
    key: "status",
    label: "Status",
    description: "Файл статуса и опционально интервал, например /var/log/openvpn/status.log 10.",
    type: "text",
    placeholder: "/var/log/openvpn/status.log",
  },
  {
    key: "log",
    label: "Log",
    description: "Файл лога OpenVPN (перезапись).",
    type: "text",
    placeholder: "/var/log/openvpn/openvpn.log",
  },
  {
    key: "log-append",
    label: "Log-append",
    description: "Файл лога с дописыванием.",
    type: "text",
    placeholder: "",
  },
  {
    key: "plugin",
    label: "Plugin (по одной строке)",
    description: "Модуль и аргументы инициализации, каждая строка — отдельная директива plugin.",
    type: "textarea",
    placeholder: "/usr/lib/openvpn/openvpn-plugin-auth-pam.so login",
  },
  {
    key: "up",
    label: "Up",
    description: "Скрипт после поднятия TUN/TAP.",
    type: "text",
    placeholder: "",
  },
  {
    key: "down",
    label: "Down",
    description: "Скрипт после опускания TUN/TAP.",
    type: "text",
    placeholder: "",
  },
  {
    key: "persist-key",
    label: "Persist-key",
    description: "Не перечитывать ключи при рестарте OpenVPN.",
    type: "checkbox",
  },
  {
    key: "persist-tun",
    label: "Persist-tun",
    description: "Сохранять TUN/TAP при рестарте.",
    type: "checkbox",
  },
  {
    key: "duplicate-cn",
    label: "Duplicate-cn",
    description: "Разрешить несколько сессий с одним и тем же CN.",
    type: "checkbox",
  },
  {
    key: "client-to-client",
    label: "Client-to-client",
    description: "Разрешить трафик между клиентами VPN.",
    type: "checkbox",
  },
  {
    key: "float",
    label: "Float",
    description: "Разрешить смену IP клиента без переподключения сертификата.",
    type: "checkbox",
  },
  {
    key: "data-ciphers",
    label: "Data-ciphers",
    description: "Список шифров данных (OpenVPN 2.5+), например AES-256-GCM:AES-128-GCM.",
    type: "text",
    placeholder: "AES-256-GCM:AES-128-GCM",
  },
  {
    key: "tls-ciphersuites",
    label: "TLS-ciphersuites",
    description: "Наборы TLS 1.3 для управляющего канала (если используется).",
    type: "text",
    placeholder: "",
  },
  {
    key: "cipher",
    label: "Cipher (legacy)",
    description: "Устаревшая директива cipher; для новых установок предпочтительно data-ciphers.",
    type: "text",
    placeholder: "",
  },
  {
    key: "auth",
    label: "Auth (HMAC)",
    description: "Алгоритм HMAC для tls-auth/tls-crypt канала, например SHA256.",
    type: "text",
    placeholder: "SHA256",
  },
  {
    key: "tls-version-min",
    label: "Мин. версия TLS",
    description: "Например 1.2 или 1.3.",
    type: "text",
    placeholder: "1.2",
  },
  {
    key: "verb",
    label: "Verb",
    description: "Уровень детализации лога OpenVPN сервера (0–11).",
    type: "number",
    placeholder: "3",
  },
  {
    key: "client-verb",
    label: "Client-verb",
    description: "Уровень детализации лога в клиентском .ovpn (0–11). В server.conf не применяется.",
    type: "number",
    placeholder: "3",
  },
  {
    key: "mute",
    label: "Mute",
    description: "Подавить повторяющиеся сообщения после N раз.",
    type: "number",
    placeholder: "20",
  },
  {
    key: "mute-replay-warnings",
    label: "Mute-replay-warnings",
    description: "Не засорять лог предупреждениями о replay.",
    type: "checkbox",
  },
  {
    key: "script-security",
    label: "Script-security",
    description: "Уровень запуска скриптов (0–3).",
    type: "number",
    placeholder: "2",
  },
  {
    key: "reneg-sec",
    label: "Reneg-sec",
    description: "Переодическое согласование ключей, секунды.",
    type: "number",
    placeholder: "0",
  },
  {
    key: "hand-window",
    label: "Hand-window",
    description: "Окно рукопожатия TLS (сек).",
    type: "number",
    placeholder: "",
  },
  {
    key: "tun-mtu",
    label: "Tun-MTU",
    description: "MTU для туннеля.",
    type: "number",
    placeholder: "1500",
  },
  {
    key: "mssfix",
    label: "Mssfix",
    description: "Ограничение MSS для TCP через VPN.",
    type: "number",
    placeholder: "1450",
  },
  {
    key: "fragment",
    label: "Fragment",
    description: "Размер фрагментации UDP (0 — отключено).",
    type: "number",
    placeholder: "",
  },
  {
    key: "user",
    label: "User",
    description: "Пользователь ОС после инициализации (снижение привилегий).",
    type: "text",
    placeholder: "nobody",
  },
  {
    key: "group",
    label: "Group",
    description: "Группа ОС после инициализации.",
    type: "text",
    placeholder: "nogroup",
  },
  {
    key: "ifconfig-pool-persist",
    label: "Ifconfig-pool-persist",
    description: "Файл для сохранения выдачи IP клиентам.",
    type: "text",
    placeholder: "/var/log/openvpn/ipp.txt",
  },
  {
    key: "comp-lzo",
    label: "Comp-lzo",
    description: "Сжатие (устаревшее); варианты: no, adaptive, yes.",
    type: "select",
    options: [
      { value: "", label: "— не задано" },
      { value: "no", label: "no" },
      { value: "adaptive", label: "adaptive" },
      { value: "yes", label: "yes" },
    ],
  },
  {
    key: "allow-compression",
    label: "Allow-compression",
    description: "Политика компрессии (OpenVPN 2.5+): no, asym, yes.",
    type: "select",
    options: [
      { value: "", label: "— не задано" },
      { value: "no", label: "no" },
      { value: "asym", label: "asym" },
      { value: "yes", label: "yes" },
    ],
  },
  {
    key: "push",
    label: "Push (по одной строке)",
    description: "Директивы, которые сервер отправит клиенту (каждая строка — отдельный push).",
    type: "textarea",
    placeholder: "redirect-gateway def1\nroute 192.168.1.0 255.255.255.0",
  },
  {
    key: "route",
    label: "Маршруты (route)",
    description: "Статические маршруты на сервере через VPN (каждая строка: сеть маска или полная форма).",
    type: "textarea",
    placeholder: "10.10.0.0 255.255.0.0",
  },
];
